development:
  adapter: postgresql
  encoding: unicode
  database: ihwc_development
  pool: 5
  username: userdb
  password: Hfo09$3bb
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: ihwc
  pool: 50
  username: userdb
  password: Hfo09$3bb
  host: localhost
  port: 5432
